# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx4G -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
org.gradle.daemon=false
org.gradle.caching=false
org.gradle.parallel=true

systemProp.file.encoding=utf-8

####################
#### Mod pages ####
##################
curseforgeid=955545
modrinthid=dimthreads
versiontype=release

#########################
#### Mod properties ####
#######################
modid=dimthread
modname=DimThreads
modversion=1.2.2
modauthor=SrRapero720
modcredits=CCr4ft3r as the original port author of Dimensional Threading Reforged, which is a Forge port of the Fabric Mod Dimensional Threading that was originally created by WearBlackAllDay
modlicense=LGPLv3
group=me.srrapero720
mod_description=Many dimensions? This mod optimizes it all assigning each dimension their own thread

#####################
#### Enviroment ####
###################
modloader=FORGE
mcversion=1.20.1
mcrange=[1.20.1,1.20.2)
# 47.2.17 is 1.20.1,
# 43.3.5 is 1.19.2,
# 40.2.17 is 1.18.2
fgversion=47.4.4
fgrange=[47,48)
fgloaderrange=[47,48)
mappingsch=parchment
mappings_version=2023.09.03-1.20.1

#######################
#### Placeholders ####
#####################
mixin_file_suffix=mixin.json
mixin_refmap_suffix=refmap-mixin.json

# github information
github_project=SrRapero720/dimthreads